### PR TITLE
[16.0][MIG] account_invoice_overdue_warn_sale

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
Requires https://github.com/OCA/credit-control/pull/266

**Review by Bearnard21 — COMMENTED** [review]
Runboat failed.
Unable to make a functional review.

**Comment by legalsylvain** [comment]
Hi @alexis-via : FYI, to make the PR working (CI + runboat)

1) update / create the file ``./test_requirements.txt`` adding a line : 
``git+https://github.com/OCA/credit-control@refs/pull/266/head#subdirectory=setup/account_invoice_overdue_warn``

2) Commit that changes with an explicit message like "[TEMP] Temporary reference to unmerged PR"

3) Once #266 is merged, you can drop the commit and rebase your PR.

(note : it works only if the setup/module_name folder existing in the other PR, but that's the case here).

**Review by GabbasovDinar — APPROVED** [review]
Migration code LGTM

**Review by Bearnard21 — CHANGES_REQUESTED** [review]
Please check the code to launch runboat for functional review

**Comment by ivs-cetmix** [comment]
Hello @alexis-via 
Thank you for your contribution! Could you please update your PR to fix the falling tests?

**Review by GabbasovDinar — CHANGES_REQUESTED** [review]
please, fix tests errors

**Pull request closed without merging**
