### PR TITLE
[16.0][MIG] sale_payment_sheet_financial_risk: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
Standard migration to v16
Depends on [#2554](https://github.com/OCA/sale-workflow/pull/2554)

@Tecnativa

 TT44358

@pedrobaeza @carlosdauden

### CODE REVIEW

**Comment by pedrobaeza** [comment]
/ocabot migration sale_payment_sheet_financial_risk

For adding temporary dependencies, see https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by carolinafernandez-tecnativa** [comment]
ping @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Please squash administrative commits

**Comment by carolinafernandez-tecnativa** [comment]
> Please squash administrative commits

done

**Comment by pedrobaeza** [comment]
I still see some of them, but wait for squashing them until the dependency is merged, and then you remove also the temporary commit.

**Comment by carolinafernandez-tecnativa** [comment]
> I still see some of them, but wait for squashing them until the dependency is merged, and then you remove also the temporary commit.

Dependency has merged and squashed administrative commits

**Comment by carolinafernandez-tecnativa** [comment]
ping @carlosdauden

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
