### PR TITLE
[16.0][MIG] account_financial_risk: Migration to version 16.0

### PR DESCRIPTION
**Pull request by ernesto-garcia-tecnativa**
@tecnativa TT44196

### CODE REVIEW

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza @chienandalu please review

**Review by carlosdauden — APPROVED** [review]
Change commit message
Migration to 15.0 >> Migration to 16.0

**Comment by ernesto-garcia-tecnativa** [comment]
> Change commit message Migration to 15.0 >> Migration to 16.0

Done, sorry

**Review by chienandalu — APPROVED** [review]
Tested :+1: Thanks :)

**Pull request merged**
