### PR TITLE
[16.0][MIG] stock_financial_risk

### PR DESCRIPTION
**Pull request by Urvisha-OSI**
Depends on:
- [x] https://github.com/OCA/credit-control/pull/292

### CODE REVIEW

**Comment by dreispt** [comment]
@Urvisha-OSI are you planning to fix the tests?

**Comment by Urvisha-OSI** [comment]
@dreispt 
the test fails because of depends module is not available in the branch

**Comment by alan196** [comment]
@Urvisha-OSI you will continue with this PR?... the module account_financial_risk is now merged, please rebase and mix the latest 4 commits in 1 commit for migration

**Pull request closed without merging**
