### PR TITLE
[14.0][MIG] account_invoice_overdue_reminder: Add credit notes to overdue e-mail

### PR DESCRIPTION
**Pull request by carmenbianca**
Port of #226

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Hi @carmenbianca , why don't you remove the unreconciled button like you did in https://github.com/OCA/credit-control/pull/226/commits/896445e0a7ee7a538e9605495785249d3995ca7c?

**Comment by carmenbianca** [comment]
I think I made an error if I didn't port something. I'll look at it later.

**Comment by carmenbianca** [comment]
I did make an error somehow. I want to blame `oca-port`, but I'm not sure. In any case, added the missing commit. Thanks for the catch @MiquelRForgeFlow !

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by carmenbianca** [comment]
This probably needs a look-see.

**Comment by carmenbianca** [comment]
Hi @alexis-via, can you take a look at this?

**Review by AaronHForgeFlow — APPROVED** [review]
Code :+1:

**Pull request merged**
