### PR TITLE
[12.0][IMP] Add selection: choose which currency should be used in risk

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/credit-control/pull/70.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional tests LGTM

**Review by marcelsavegnago — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please forward-port it to v13 as well. @JordiBForgeFlow can you please change the default branch of the repo to 13.0?

**Pull request merged**
