### PR TITLE
[13.0][MIG]account_invoice_overdue_reminder

### PR DESCRIPTION
**Pull request by manuelregidor**
Backport to 13.0

### CODE REVIEW

**Comment by manuelregidor** [comment]
@ValentinVinagre @HaraldPanten

**Comment by alexis-via** [comment]
I fixed a string in this PR: https://github.com/sygel-technology/credit-control/pull/1
Otherwise, works well.

**Comment by ValentinVinagre** [comment]
> I fixed a string in this PR: [sygel-technology#1](https://github.com/sygel-technology/credit-control/pull/1) Otherwise, works well.

Merged & thanks 😃

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
