### PR TITLE
[14.0][FIX] account_financial_risk: Cherry-pick v13 PRs 138 and 152

### PR DESCRIPTION
**Pull request by carlosdauden**
cherry-pick https://github.com/OCA/credit-control/pull/138
cherry-pick from https://github.com/OCA/credit-control/pull/152

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's fast-track for equaling branches. Now only v15 is missing:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Ouch, Travis is red, so you have to fix it first.

**Comment by carlosdauden** [comment]
Travis green now

**Comment by pedrobaeza** [comment]
Great!

/ocabot merge nobump

Please remember the fw-port to v15

**Pull request merged**
