### PR TITLE
[13.0][IMP] account_invoice_overdue_reminder: decouple mail validation and vals generation

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Small improvement to allow inheritance of the mail validation method

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LG!

**Comment by AaronHForgeFlow** [comment]
/ocabot merge patch

Can you please forward port it?

**Comment by JordiMForgeFlow** [comment]
Hi @AaronHForgeFlow 

FW in https://github.com/OCA/credit-control/pull/216 :)

**Pull request merged**
