### PR TITLE
[14.0][MIG] account_credit_control

### PR DESCRIPTION
**Pull request by naglis**
Some notes:
- Tried to combine the _OCA Transbot..._ commits, but it results in rebase conflicts so I have left it as is. If anyone wants to have a go, please feel free.
- Removed `rel` field parameter from fields as it is not the correct one (`relation`) and now Odoo logs a warning about it.
- Please revise `ir.model.access` records added for the wizards (from functionality perspective, what groups should have what access to what wizards).

### CODE REVIEW

**Comment by naglis** [comment]
The [failing test](https://app.travis-ci.com/github/OCA/credit-control/jobs/524148557#L1238) [`test_invoices`](https://github.com/OCA/credit-control/blob/14.0/account_financial_risk/tests/test_account_financial_risk.py#L146) from Travis seems to be from another addon `account_financial_risk`.

**Comment by tarbib** [comment]
Hello @naglis,
Thanks for the migration
It looks like the communication is not created, see my test :

https://user-images.githubusercontent.com/2255433/127333069-53b20baf-f6a1-457f-9910-79d5dfd30c92.mp4

**Comment by naglis** [comment]
Hello @tarbib, thank you for your test. I did mostly technical migration and I am not very familiar with how `account_credit_control` is supposed to work, so from your test video it is a bit unclear to me what was the expected result. Could you please provide a textual description of what behavior was expected and what was the actual behavior on Runbot?

**Comment by tarbib** [comment]
https://user-images.githubusercontent.com/2255433/127346090-be9a49aa-77ac-438b-98ae-a7346358faae.mp4

@naglis thanks for your answer, you can check a similar test on v13. 
When clicking on "run channel action" (1:06 min) it will generate "communications"
i.e : email to be sent to the partners.

**Comment by naglis** [comment]
@tarbib thank you. I made a mistake in the initial migration and not all the latest changes of `account_credit_control` from `13.0` were included (including the communications). I've included all the commits now.

**Review by tarbib — APPROVED** [review]
Functional test ok :+1: 

https://user-images.githubusercontent.com/2255433/127448422-0061508b-725a-47a4-9242-f433a48f7bd1.mp4

**Comment by tarbib** [comment]
@naglis thanks ! Your build is failing though

**Comment by naglis** [comment]
Yes, a test of another `account_financial_risk` is failing:
```
2021-07-28 22:00:04,728 5749 ERROR openerp_test odoo.addons.account_financial_risk.tests.test_account_financial_risk: FAIL: TestPartnerFinancialRisk.test_invoices
Traceback (most recent call last):
File "/home/travis/build/OCA/credit-control/setup/account_financial_risk/odoo/addons/account_financial_risk/tests/test_account_financial_risk.py", line 146, in test_invoices
self.assertAlmostEqual(self.partner.risk_invoice_open, 550.0)
AssertionError: 0.0 != 550.0 within 7 places
```

I am not sure if this is due to this PR (the addons do not depend on one another). If you have any ideas, please share.

**Comment by tarbib** [comment]
@naglis Sorry I don't know and I'm not a developer. Maybe @pedrobaeza has an idea?

**Comment by pedrobaeza** [comment]
Fixed upstream test in cc459b7a1178fd805ce3d141e801103ebfef1ea2. You can rebase.

**Review by ernestotejeda — APPROVED** [review]

**Pull request merged**
