### PR TITLE
[IMP] account_invoice_overdue_reminder: allow to remove some undesired invoices on the fly during reminder process

### PR DESCRIPTION
**Pull request by legalsylvain**
**Summary**
This PR improve the module ``account_invoice_overdue_reminder`` to allow user to remove manually one or many invoices. This will recompute automatically the field ``counter``, and let user manually regenerate body and subject mail. (if reminder type is email)

**Use Case**
- Your customer has several invoices to pay. For one invoice, there is a pending conflict (customer think that the delivered products or the service is not ok, ...) You want to send a reminder without the conflictual invoice.
- Your customer has several invoices to pay. One of the invoice has been confirmed and sent late from your part. So you don't want to send a reminder for this invoice, but for the others.

**Screenshots**

**Step 1** : The wizard display all the invoices. The user can remove on or many invoices.

image

**Step2 ** : when an invoice is removed, counter is refreshed and an message is displayed to recompute email info. (title & body)

image

**Step 3** : Once clicked, the email info are updated. 

image

**Technical point**
- ``counter`` can be recomputed on the fly with a classic ``onchange`` function. However, recompute body is not possible in an 
- ``onchange`` function, because ``self.id`` is ``Newid`` in this context, making not possible the call of the function ``_render_template(..., res_id)``. For that reason a button is displayed.

Perhaps such workaround may be removed in more recent version of Odoo (with the refactor of onchange / depends core features).

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @alexis-via : Following my phone call this morning, here is a proposal from PR.

Thanks for your review !

**Comment by legalsylvain** [comment]
@alexis-via @OCA/accounting-maintainers : could you take a look on that one. It is working well and in production since 4 monthes.

**Review by sergiocorato — APPROVED** [review]
LGTM

**Pull request merged**
