### PR TITLE
[17.0][MIG] account_invoice_overdue_warn: Migration to 17.0

### PR DESCRIPTION
**Pull request by RogerSans**
Standard migration
T-6277

@HaraldPanten 
@ValentinVinagre

### CODE REVIEW

**Review by Jaimermaccione — COMMENTED** [review]
@RogerSans The module works well but I see that the image in the README is not showing. I don't know if it's a temporary issue because it's a provisional version or if it needs to be linked correctly. Could you please check it? If everything is fine, let me know to give it the definitive review. Thanks!

**Review by Jaimermaccione — APPROVED** [review]
LGTM! Functional review on runboat :+1: 

@RogerSans

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
