### PR TITLE
[13.0][IMP] account_financial_risk: Add specific overpassing group

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
* specific group for overpassing partner credit limit exceprtions

Forward port #99

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please name the commit correctly. It's not `[UPT]`, but `[IMP]`, and put the explanation in the commit message itself:

```
[IMP] account_financial_risk: Add specific overpassing group


This commit adds an specific group for overpassing partner credit limit exceptions

In some situations, not only account managers shoud be allowed to overpass exception, depending on the company policies. Merging this code will not affect current instances, as long as account managers will be added to the new group.
```

Please don't be lazy :stuck_out_tongue_closed_eyes:

**Comment by AaronHForgeFlow** [comment]
haha, looking forward invoking ocabot to do the forward ports :innocent:

**Comment by pedrobaeza** [comment]
Well, this comment should be in the original PR as well, but I don't want to be always the bad guy after being approved by 2/3 people, but this time being in upper versions that will still have a way, better to stick to guidelines:

https://www.odoo.com/documentation/14.0/reference/guidelines.html#commit-message-structure

**Comment by AaronHForgeFlow** [comment]
sure, agree.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
