### PR TITLE
[IMP] account_financial_risk: problems of partner view are fixed

### PR DESCRIPTION
**Pull request by ernesto-garcia-tecnativa**

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
You should put an screenshot of the before and after.

**Comment by ellbristow** [comment]
I've checked #295 and it is perfectly acceptable. I'll add some screenshots to that one on behalf of the author.

This PR can be closed

**Comment by ellbristow** [comment]
> You should put an screenshot of the before and after.

Before:
image

After:
image

**Review by ellbristow — APPROVED** [review]
LGTM (for what it's worth)

**Review by pedrobaeza — APPROVED** [review]
Thanks

/ocabot merge minor

**Pull request merged**
