### PR TITLE
[16.0][IMP] account_invoice_overdue_reminder: hide button if reminded

### PR DESCRIPTION
**Pull request by astirpe**
Implements https://github.com/OCA/credit-control/issues/328

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks ! 

Nice to have : could you update a test to check the value of the new 'overdue_remind_sent' field ?

**Review by carlosdauden — APPROVED** [review]

**Comment by astirpe** [comment]
@legalsylvain thank you! I didn't update tests because I can't find tests for this module..

**Comment by astirpe** [comment]
@ThijsvOers do you mind to check this fix in runboat?

**Comment by legalsylvain** [comment]
> @legalsylvain thank you! I didn't update tests because I can't find tests for this module..

Oh ! I see ! https://app.codecov.io/gh/OCA/credit-control/tree/16.0

image

To be fixed in another PR. I'll take a look on that topic on oca days.

**Comment by astirpe** [comment]
Just added a `compute_sudo` to avoid a warning in the log: `inconsistent 'compute_sudo' for computed fields`

**Review by ThijsvOers — APPROVED** [review]
tested and ok

**Comment by astirpe** [comment]
In the Odoo Experience I did learn that having one computed method for both stored and non-stored fields is a bad practice. So with https://github.com/OCA/credit-control/pull/329/commits/6e575dc31dfddcb8125effd9c310076f7f1f5692 I'm splitting the compute method.

**Comment by legalsylvain** [comment]
hi maintainers. Could you merge this one ? 
Thanks ! 

@OCA/accounting-maintainers

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
