### PR TITLE
[16.0][IMP] account_financial_risk: FW-Port two commits from v14

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT44497

@carlosdauden please review!

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @stefan-tecnativa ,

Please could you please rebase in order to resolver conflicts and see if all green and we can test it ?

Thank you!

**Comment by pedrobaeza** [comment]
@stefan-tecnativa you have to adapt the commits to the v16 specificity.

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@stefan-tecnativa there are conflicting files, can you rebase and fix them?

**Review by Shide — APPROVED** [review]

**Pull request merged**
