### PR TITLE
[WIP][MIG][13.0] sale_financial_risk: Migration to v13.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
depends on https://github.com/OCA/credit-control/pull/52
TT21659

### CODE REVIEW

**Review by alan196 — APPROVED** [review]
👍 Tested locally and technical review

**Comment by pedrobaeza** [comment]
Please include #60

**Comment by pedrobaeza** [comment]
Wait until checked why it has been duplicated

**Comment by pedrobaeza** [comment]
@MiquelRForgeFlow why do you duplicate this pr?

**Comment by MiquelRForgeFlow** [comment]
Oh, I didn't see it, sorry. By inertia I followed with the migration of modules. By the way, this PR have to add last commits of @carlosdauden .

**Comment by pedrobaeza** [comment]
Let's merge first the main module and then value which is the work to bring latest improvements here.

**Comment by pedrobaeza** [comment]
Finally closing in favor of #68

**Pull request closed without merging**
