### PR TITLE
[14.0] [FIX] account_invoice_overdue_reminder : add mail.mail  read access for biiling user

### PR DESCRIPTION
**Pull request by abenzbiria**
Fix for issue https://github.com/OCA/credit-control/issues/366

### CODE REVIEW

**Comment by abenzbiria** [comment]
Hi @pedrobaeza .

Could you please have a look at this PR.

Thank you

**Comment by pedrobaeza** [comment]
Sorry, I don't use this module.

**Comment by abenzbiria** [comment]
Hi @alexis-via , @AaronHForgeFlow , @MiquelRForgeFlow

Could you please have a look at this PR.

Thanks  for  help

**Comment by alexis-via** [comment]
Thanks for your bug report. Isn't it too generous to give read access to mail.mail ?
I see that, by default, only the base.group_system has read access on mail.mail...
Do we have another option, like using a sudo() ?

**Pull request closed without merging**
