### PR TITLE
[15.0] [MIG] account_invoice_overdue_reminder

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please cherry-pick https://github.com/OCA/credit-control/commit/7798ded4120ea054067c9e464a11ecb2c7616cdd.

**Comment by JasminSForgeFlow** [comment]
> Please cherry-pick [7798ded](https://github.com/OCA/credit-control/commit/7798ded4120ea054067c9e464a11ecb2c7616cdd).

Done, Thanks

**Comment by JuanyDForgeflow** [comment]
@JasminSForgeFlow I got this error while trying to confirm the invoice

AttributeError: 'account.move' object has no attribute 'invoice_payment_state'

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow I got this error while trying to confirm the invoice
> 
> AttributeError: 'account.move' object has no attribute 'invoice_payment_state'

Fixed, Thanks

**Comment by JordiMForgeFlow** [comment]
Hi @JasminSForgeFlow 

Could you add https://github.com/OCA/credit-control/pull/212? Thanks!! :)

**Comment by JasminSForgeFlow** [comment]
> Hi @JasminSForgeFlow
> 
> Could you add #212? Thanks!! :)

Done, Thanks

**Review by JuanyDForgeflow — APPROVED** [review]
Functional review LGTM

**Comment by MiquelRForgeFlow** [comment]
Added https://github.com/OCA/credit-control/pull/222.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Functional LG!

**Pull request merged**
