### PR TITLE
[14.0][MIG] account_invoice_overdue_reminder

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by patel1008b** [comment]
@alexis-via  thanks for this module.

Is there any plan for v13 as well?

**Comment by alexis-via** [comment]
@bhaveshselarka It's not in my plans at the moment, but feel free to do it. Backporting the module from v14 to v13 should be quite easy.

**Comment by mgielissen** [comment]
> @bhaveshselarka It's not in my plans at the moment, but feel free to do it. Backporting the module from v14 to v13 should be quite easy.

I have the backport from v14 to v13 almost ready.

https://github.com/mgielissen/overdue_reminder/tree/13-mig-overdue-reminder

Update: Backport is ready

**Comment by rconjour** [comment]
@alexis-via can you please squash the last two commits?

**Comment by alexis-via** [comment]
No, the commit for reformatting with black must be in a separate commit.

**Review by tarbib — APPROVED** [review]
Functional test :+1: 

https://user-images.githubusercontent.com/2255433/127461118-9f94a845-8016-411c-af7d-ba381fce885d.mp4

**Comment by pedrobaeza** [comment]
There's an error in current merged modules tests. I'm fixing it.

**Comment by alexis-via** [comment]
ok, thank you Pedro !

**Comment by pedrobaeza** [comment]
Fixed in cc459b7a1178fd805ce3d141e801103ebfef1ea2. You can relaunch.

**Pull request merged**
