### PR TITLE
12.0 mig stock financial risk

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa

Depends on https://github.com/OCA/credit-control/pull/12

### CODE REVIEW

**Comment by ernestotejeda** [comment]
I included the commits of https://github.com/OCA/credit-control/pull/12 until it is merged

**Review by pedrobaeza — COMMENTED** [review]
Can you apply the same technique for getting full history than on `account_financial_risk`? That can be done when the other module is merged for avoiding additional difficulties due to this.

**Comment by pedrobaeza** [comment]
Rebase and try the method for preserving whole history

**Comment by ernestotejeda** [comment]
> Rebase and try the method for preserving whole history

Done

**Review by pedrobaeza — APPROVED** [review]

**Review by yajo — APPROVED** [review]

**Pull request merged**
