### PR TITLE
[14.0][IMP/FIX] account_finacial_risk: add improvements

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
First commit is a forward port.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review :+1:  LGTM

**Comment by MiquelRForgeFlow** [comment]
@carlosdauden please, could you check and approve? :)

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by carlosdauden** [comment]
Can you change `def action_post(self):` by `def _post(self, soft=True):`?
I commented here: https://github.com/OCA/credit-control/pull/160#discussion_r755951071

This wizard call to method _post:
https://github.com/odoo/odoo/blob/37481a9f797e6dc519405aef1e6196a9e76a9203/addons/account/wizard/account_validate_account_move.py#L22
therefore method _post should be extended, and not action_post, to the warning is displayed when several invoices are validated

**Comment by MiquelRForgeFlow** [comment]
@carlosdauden sorry, I didn't see that comment. It's done and ready! :)

**Comment by MiquelRForgeFlow** [comment]
it's green now!

**Review by carlosdauden — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Thank you for reviewing! Merging, as approved by the maintainer.

/ocabot merge minor

**Comment by AaronHForgeFlow** [comment]
wtf

**Pull request merged**
