### PR TITLE
[13.0][IMP] sale_financial_risk: Change related risk partner target and rename field

### PR DESCRIPTION
**Pull request by carlosdauden**
This change allow compute risk for partner invoice to finish https://github.com/OCA/credit-control/pull/92

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
For performance reasons on existing installations, you need to add a pre-migration script that call the same hook than on post-install.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@carlosdauden plase make the change on performance part and we can merge this.

**Comment by carlosdauden** [comment]
@pedrobaeza Changes done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
