### PR TITLE
[IMP] account_invoice_overdue_reminder: Add credit notes to overdue e-mail

### LINKED ISSUE #211: account_invoice_overdue_reminder: include the credit notes in the process
**Is your feature request related to a problem?**
One of our customers would like to include the credit notes in the process. Here is why. They invoice twice a week all their customers. After delivery of products, they create credit notes. They don't reconcile the credit note with the invoice until the customer pays one of the due invoices and decide to deduct the credit note amount. It's not always 1 invoice - 1 credit note in the way their customer decide to pay. Once the credit note is deducted by the customer from the invoice of his choice, the matching is done in Odoo and the credit note is marked as "paid".

**Describe the solution you'd like**
The account_invoice_overdue_reminder could have an additionnal configuration "do you want to include open credit notes in the reminder process?"
If no => no change to current behavior
If yes => the open credit notes are included in the list of due invoices and in the table in the mail template. In addition, the checkbox "To check if unreconciled payments/refunds above have a good reason not to be reconciled with an open invoice" is not displayed (because not useful, the user would need to always check it manually).

**Describe alternatives you've considered**
Instead of including this credit note feature in the module, we could add it in a separate module.

**Additional context**
We can do the described development and propose it in this repo. Please advise if it can be useful to others and if a separate module would be best or not.
Thanks!
@alexis-via I'd be glad to get your feedback here.
@carmenbianca for follow-up next weeks when I'm off.

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #211 

Screenshot. I am not a UI designer.

Capture d’écran du 2022-11-30 15-17-31

(I added a 'type' column. Maybe it's not necessary.)

Internal task: https://gestion.coopiteasy.be/web#id=9074&action=479&model=project.task&view_type=form&menu_id=536

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks ! 

@alexis-via, @sergiocorato : could you take a look on this one ?

**Review by sergiocorato — APPROVED** [review]
LGTM

**Comment by sergiocorato** [comment]
To proceed to merge the branch needs to be upgraded to copier template, I'll do it.

**Comment by sergiocorato** [comment]
@legalsylvain @alexis-via @carmenbianca I added #232 to fix this.

**Comment by carmenbianca** [comment]
Changed the colour to LightGray.

Also fixed a restraint.

**Comment by legalsylvain** [comment]
Could you rebase ?

**Comment by carmenbianca** [comment]
@legalsylvain rebased

@alexis-via could you merge this when you next have time?

---

n.b. future users -> the mail template is marked noupdate. In order to get the new mail template, you have to run `odoo [...] -i account_invoice_overdue_reminder`. furthermore, the translations are not yet done.

**Comment by carmenbianca** [comment]
Bump :)

**Comment by vdewulf** [comment]
@carmenbianca what needs to be done to get this merged? thx!

**Comment by rvalyi** [comment]
hello as usual I guess we lack of reviewer and active repo PSC'... PRs authors can also always increase their chance to get a review by helping the module maintainers/authors or key reviewers in some of their own PRs but people like Alexis are busy like hell anyway...

Based on the reviews and the fact you discussed the feature with @alexis-via the module author I'll merge it tough. Would be cool if you could port it to newer versions too. To be honest chances Alexis review PRs on v13 or v15s are low, but v14 and v16 PRs would have a chance.

/ocabot merge minor

**Comment by vdewulf** [comment]
@rvalyi thanks a lot! @carmenbianca will port this to v14 as suggested!

**Pull request merged**
