### PR TITLE
[IMP] account_credit_control: Set multicompany usage. Remove warnings

### PR DESCRIPTION
**Pull request by etobella**
Cherry-pick of #94

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There seems to be a problem in Travis with pre-commit download. It's affecting all 13.0+ builds.

**Review by albariera — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by etobella** [comment]
@OCA/accounting-maintainers  can you check? it is a cherry-pick

**Review by carlosdauden — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by etobella** [comment]
Weird, everything went successful on travis...

**Comment by pedrobaeza** [comment]
It seems a Travis glitch:

/ocabot merge minor

**Pull request merged**
