### PR TITLE
[12.0] [REF] Simplify get_level_lines on CreditControlPolicyLevel

### PR DESCRIPTION
**Pull request by qgroulard**
Remove the distinction between first level and other level policy lines.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
@rousseldenis maybe adding the version change in manifest as my only remark, the code looks good.

**Comment by rousseldenis** [comment]
> @rousseldenis maybe adding the version change in manifest as my only remark, the code looks good.

Hey, as we have for some weeks the oca bot 'merge' command, we can with that pass argument 'major|minor|patch' to update module version. So, maintainer will do it (reviewers has less work :smiley: )

**Comment by houssine78** [comment]
> 
> 
> > @rousseldenis maybe adding the version change in manifest as my only remark, the code looks good.
> 
> Hey, as we have for some weeks the oca bot 'merge' command, we can with that pass argument 'major|minor|patch' to update module version. So, maintainer will do it (reviewers has less work 😃 )

interesting ! where did you pass such argument ?

**Comment by rousseldenis** [comment]
> > > @rousseldenis maybe adding the version change in manifest as my only remark, the code looks good.
> > 
> > 
> > Hey, as we have for some weeks the oca bot 'merge' command, we can with that pass argument 'major|minor|patch' to update module version. So, maintainer will do it (reviewers has less work smiley )
> 
> interesting ! where did you pass such argument ?

In fact, it is used as github PR comment. But you need merge rights to use it.

See for example : https://github.com/OCA/stock-logistics-warehouse/pull/726#issuecomment-535932144

**Comment by qgroulard** [comment]
@OCA/core-maintainers , This PR is ready to merge

**Pull request merged**
