### PR TITLE
[14.0] FIxes sale_financial_risk: Don't duplicate settings box

### PR DESCRIPTION
**Pull request by gdgellatly**
Before this commit you got a slighly offset layout in the config view.

After this layout, it is nice and standard.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe a screenshot of before and after?

**Comment by gdgellatly** [comment]
Well here they are - but it should be obvious that you can't put a setting box in a setting box.
image

image

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
And you get a fast-tracking as bonus for showcasing the problem :wink: 

/ocabot merge minor

**Comment by pedrobaeza** [comment]
Cherry-picked whole feature with the patch included to v15 at 22ea4f6b83ffc0005fe94a57f0501117c1928d64. Previously, I needed to fix tests, as they were not being reported as incorrect at dd205ccb01250d49d2c58e473bd2c4c5d013f20f

**Pull request merged**
