### PR TITLE
[15.0][IMP] account_credit_control: Add Payment Reference from invoice to communication table

### PR DESCRIPTION
**Pull request by victoralmau**
Changes done:
- [x] **IMP**: Add Payment Reference from invoice to communication table (FWP from 14.0: https://github.com/OCA/credit-control/pull/289)
- [x] **FIX**: Add table to email content

@Tecnativa TT41337

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this still draft?

**Comment by victoralmau** [comment]
Creating this change I have found that it does not add the table to the email that is sent and that is what I am reviewing and trying to resolve.

**Comment by victoralmau** [comment]
Now it's fixed and ready for review

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by bosd** [comment]
Would like to update some translations.
It seems this PR has locked weblate, due to merge conflict.
https://translation.odoo-community.org/projects/credit-control-15-0/credit-control-15-0-account_credit_control/#alerts

Can someone with superpowers look into this?? :pray:

**Comment by pedrobaeza** [comment]
@bosd unlocked.

**Pull request merged**
