### PR TITLE
[FIX][16.0] account_invoice_overdue_reminder: remind partially paid invoices

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/credit-control/issues/330

CC @ThijsvOers @Yvesldff

### CODE REVIEW

**Review by ThijsvOers — COMMENTED** [review]
Tested this on Runboat, the overdue tab is now visible after partial payment. I will approve the issue

**Review by legalsylvain — APPROVED** [review]

**Review by ThijsvOers — APPROVED** [review]
Tested on runboat and ok

**Comment by astirpe** [comment]
Can this one be merged?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — COMMENTED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
