### PR TITLE
[15.0][ADD] sale_financial_risk_confirm_action: New module

### PR DESCRIPTION
**Pull request by carlosdauden**
ping @sergio-teruel @CarlosRoca13 

@Tecnativa TT49745

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Review by sergio-teruel — CHANGES_REQUESTED** [review]
Can you add some test??

**Comment by sergio-teruel** [comment]
@pedrobaeza Can you re-open please??

**Comment by pedrobaeza** [comment]
GitHub is not allowing me to do it. You should create another PR.

**Comment by carlosdauden** [comment]
It was "reopened" and reviewed here https://github.com/OCA/credit-control/pull/416 :wink:

**Pull request closed without merging**
