### PR TITLE
[13.0][IMP] account_invoice_overdue_reminder: add the method to get the attachment_ids

### PR DESCRIPTION
**Pull request by JudithAforgeFlow**
In case you want to attach specific invoices to the reminder email it is more convenient to have a dedicated method.

CC @ForgeFlow

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
Hooks are always welcome :+1:

**Review by JordiMForgeFlow — APPROVED** [review]
Code LGTM 👍🏼

**Comment by MiquelRForgeFlow** [comment]
@JudithAforgeFlow conflicts. please rebase :)

EDIT: I did it.

**Review by adrienpeiffer — APPROVED** [review]

**Pull request merged**
