### PR TITLE
[16.0][FIX] account_credit_control: avoid AccessError in open_credit_lines()

### PR DESCRIPTION
**Pull request by astirpe**
This fixes the error described by @grindtildeath in https://github.com/OCA/credit-control/pull/268#discussion_r1214529162

### CODE REVIEW

**Comment by nilshamerlinck** [comment]
Hello @astirpe might be worth taking the occasion to fix `open_credit_communications()` as well?

**Comment by astirpe** [comment]
@nilshamerlinck you are right. Done!

**Review by nilshamerlinck — APPROVED** [review]

**Review by grindtildeath — APPROVED** [review]

**Review by Yadier-Tecnativa — APPROVED** [review]
LGTM

**Pull request merged**
