### PR TITLE
[13.0][ADD] sale_financial_risk_info: New module.

### PR DESCRIPTION
**Pull request by carlosdauden**
Extends account financial risk to add consumption info in sales orders.

### CODE REVIEW

**Comment by francesco-ooops** [comment]
Hi @carlosdauden , this is good but from what I've tested, user is not aware of the SO exceeding customer's financial risk until SO is confirmed (which is somehow covered by sale_financial_risk, and providing this information before clicking "confirm" was our goal for #175 ). 

A possible improvement could be adding a new field under "risk info" named "remaining risk" and displaying the remaining amount, eg:

Risk Info 4610$ of 10000$ (46%) 
Remaining risk: 5390$

This would be good enough to make it easy for user to check whether SO total is > remaining risk before confirm, and also to use this field for automated actions if it goes below 0.

What do you think?

**Review by francesco-ooops — APPROVED** [review]
Functional review OK

**Review by SicurSam — APPROVED** [review]
LGTM

**Comment by carlosdauden** [comment]
We could add use here a system parameter:
https://github.com/OCA/credit-control/pull/178/files#diff-28133c1098af2cfe22bfacc1d6e5d779a8803bfa2c87d128d54a04f1ff81063dR32
similar to how we use it here:
https://github.com/OCA/l10n-spain/blob/9bba9dc23b0c186e556a293563115becfcad7609/l10n_es_partner/models/res_partner.py#L60-L72
https://github.com/OCA/l10n-spain/blob/9bba9dc23b0c186e556a293563115becfcad7609/l10n_es_partner/data/l10n_es_partner_data.xml#L7
to allow customize what you want to display in that field by adding the available risk as a parameter

**Comment by francesco-ooops** [comment]
> We could add use here a system parameter: https://github.com/OCA/credit-control/pull/178/files#diff-28133c1098af2cfe22bfacc1d6e5d779a8803bfa2c87d128d54a04f1ff81063dR32 similar to how we use it here: https://github.com/OCA/l10n-spain/blob/9bba9dc23b0c186e556a293563115becfcad7609/l10n_es_partner/models/res_partner.py#L60-L72 https://github.com/OCA/l10n-spain/blob/9bba9dc23b0c186e556a293563115becfcad7609/l10n_es_partner/data/l10n_es_partner_data.xml#L7 to allow customize what you want to display in that field by adding the available risk as a parameter

good for me, as long as readme explains how to use it :)
Do you want to make the change before merge?
Also what's up with precommit?

**Comment by carlosdauden** [comment]
@francesco-ooops changes done

**Comment by francesco-ooops** [comment]
> @francesco-ooops changes done

Sorry, but not being very tech-savvy, how do I make this field "risk_available" visible on SO?

**Comment by carlosdauden** [comment]
https://github.com/OCA/credit-control/pull/178/files#diff-0bab3292377715f83710587679800930ee5fbe59fc5563654ae6663e01682634R4-R6

Try to create system parameter with this value:
"<h5{text_class}>{risk_total}{symbol} / {credit_limit}{symbol} ({risk_percent}%) Remaininig {risk_available}{symbol}</h5>"
Or:
"<h5{text_class}>{risk_total}{symbol} Remaininig {risk_available}{symbol}</h5>"

**Comment by francesco-ooops** [comment]
> 

thanks, which key should I assign to the system parameter? 🙂

**Comment by pedrobaeza** [comment]
It's put on the README: `sale_financial_risk_info.info_pattern`

**Comment by francesco-ooops** [comment]
> <h5{text_class}>{risk_total}{symbol} Remaininig {risk_available}{symbol}

I tested both: 

image

Getting this error in SO: 

`  File "/mnt/data/odoo-addons-dir/sale_financial_risk_info/models/sale.py", line 21, in _compute_risk_info
    ICP.get_param("sale_financial_risk_info.info_decimals", default="0")
ValueError: invalid literal for int() with base 10: '<h5{text_class}>{risk_total}{symbol} Remaininig {risk_available}{symbol}'`

Am I doing something wrong?

**Comment by francesco-ooops** [comment]
> > <h5{text_class}>{risk_total}{symbol} Remaininig {risk_available}{symbol}
> 
> I tested both:
> 
> image
> 
> Getting this error in SO:
> 
> ` File "/mnt/data/odoo-addons-dir/sale_financial_risk_info/models/sale.py", line 21, in _compute_risk_info ICP.get_param("sale_financial_risk_info.info_decimals", default="0") ValueError: invalid literal for int() with base 10: '<h5{text_class}>{risk_total}{symbol} Remaininig {risk_available}{symbol}'`
> 
> Am I doing something wrong?

@carlosdauden btw I tested also with closed h5 tag as per readme but still getting that error

**Comment by carlosdauden** [comment]
¿Why do you set a string in info_decimal parameter?
https://github.com/OCA/credit-control/pull/178/files#diff-28133c1098af2cfe22bfacc1d6e5d779a8803bfa2c87d128d54a04f1ff81063dR20-R22
https://github.com/OCA/credit-control/pull/178/files#diff-28133c1098af2cfe22bfacc1d6e5d779a8803bfa2c87d128d54a04f1ff81063dR36

Try to use the parameter info_pattern... (closing h5, of course)

**Comment by francesco-ooops** [comment]
ahh, sorry for my (repeated) mistakes! It works well. Once precommit is fixed, it can be merged

So in your opinion, with the current setup, is there a way to trigger an automated action based on sale financial risk info field being below a certain threshold?

**Comment by carlosdauden** [comment]
You can use filtered method to evaluate any unstored computed field from desired record model.
https://www.odoo.com/documentation/15.0/developer/reference/backend/orm.html#filter

**Comment by francesco-ooops** [comment]
@carlosdauden thanks!

any idea on what's wrong with precommit?

**Pull request merged**
